apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aim-logs-pvc
  namespace: aim-framework
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aim-data-pvc
  namespace: aim-framework
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard